# AUTOGENERATED! DO NOT EDIT! File to edit: colors.ipynb.

# %% auto 0
__all__ = ['extract_colors', 'scatter_plotly', 'compress_img']

# %% colors.ipynb 1
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import numpy as np
from fastcore.all import *
from PIL import Image

# %% colors.ipynb 4
def extract_colors(img):
    arr = np.array(img)/255 # normalize to unit cube
    cols  = arr.reshape(-1, 3)
    return cols.T

# %% colors.ipynb 6
def scatter_plotly(cols):
    x,y,z = cols
    return go.Figure(data=[go.Scatter3d(x=x,y=y,z=z, mode='markers', marker=dict(size=2, color=cols.T))])

def compress_img(img, scale=256):
    w, h = img.size
    return img.resize((min(scale,w), min(scale,h)))
